// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDxFqwcCOfYSk4QavekxEFf4oIbUzkc-o',
    appId: '1:171181830258:web:c546ca3fc70f36ca3a92eb',
    messagingSenderId: '171181830258',
    projectId: 'sm-sample-one',
    authDomain: 'sm-sample-one.firebaseapp.com',
    storageBucket: 'sm-sample-one.appspot.com',
    measurementId: 'G-E4339NGVHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2sqqMkagmOp98DrdXhepTSTphZ7W6FG8',
    appId: '1:171181830258:android:80d2b704e7f93f503a92eb',
    messagingSenderId: '171181830258',
    projectId: 'sm-sample-one',
    storageBucket: 'sm-sample-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLw4UYg56nPqYpSIGMsx9Py9egf3Xn1yQ',
    appId: '1:171181830258:ios:6eb5c39f8a64b1e13a92eb',
    messagingSenderId: '171181830258',
    projectId: 'sm-sample-one',
    storageBucket: 'sm-sample-one.appspot.com',
    iosBundleId: 'com.example.smSampleOne',
  );
}
